### ISSUE TITLE
v2.0.2 not working: Illegal instruction

### ISSUE THREAD

**Issue by weidingerc** [aceisace/Inkycal#249] opened 2023-04-02 17:35 UTC
Hi all,

I wanted to update to v2.0.2 from v2.0.0.

To have a clean install I started completely new by installing the newest Raspbian OS. 
I then followed the steps described in the readme. 
Unfortunately when starting inky_run.py it always returns "Illegal instruction".

What am I doing wrong? :/

**Comment by aceisace** [comment] 2023-04-03 00:24
Hi there,
thanks for reporting this issue. Could you please provide the full traceback or a a screenshot of the error?

This issue is a bit more difficult to fix since it's basically an incompatibility between the OS and a package. In the meantime, you can try using InkcalOS from the releases page (v2.0.1)

**Comment by weidingerc** [comment] 2023-04-03 15:56
Here's the screenshot

<img width="1018" alt="Bildschirmfoto 2023-04-03 um 17 53 31" src="https://user-images.githubusercontent.com/13382038/229562735-c0daa591-36b3-45f9-81a7-f1f335a44ce4.png">

Ok, I can try 2.0.1 in the meantime.

**Comment by aceisace** [comment] 2023-04-05 01:15
Thanks for the screenshot! I'll fix this as soon as I can. It seems this is somehow very specific to the current release of Raspberry Pi OS and python. On my Mac, I cannot reproduce it, but I'll test this on my Raspberry Pi soon.

Just for reference, could you provide some additional details about the setup? Which version of Raspberry Pi python are you using? To find the python version within the virtual environment, you can type `which python` or `which python3`

**Comment by weidingerc** [comment] 2023-04-06 08:06
Ok I guess I found the issue. When I type python -v or python3 -v the following output occurs:

```
(venv) pi@raspberrypi:~/Inkycal $ python -v
import _frozen_importlib # frozen
import _imp # builtin
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
import 'posix' # <class '_frozen_importlib.BuiltinImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
# installing zipimport hook
import 'time' # <class '_frozen_importlib.BuiltinImporter'>
import 'zipimport' # <class '_frozen_importlib.FrozenImporter'>
# installed zipimport hook
# /usr/lib/python3.9/encodings/__pycache__/__init__.cpython-39.pyc matches /usr/lib/python3.9/encodings/__init__.py
# code object from '/usr/lib/python3.9/encodings/__pycache__/__init__.cpython-39.pyc'
# /usr/lib/python3.9/__pycache__/codecs.cpython-39.pyc matches /usr/lib/python3.9/codecs.py
# code object from '/usr/lib/python3.9/__pycache__/codecs.cpython-39.pyc'
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import 'codecs' # <_frozen_importlib_external.SourceFileLoader object at 0xb678ba90>
# /usr/lib/python3.9/encodings/__pycache__/aliases.cpython-39.pyc matches /usr/lib/python3.9/encodings/aliases.py
# code object from '/usr/lib/python3.9/encodings/__pycache__/aliases.cpython-39.pyc'
import 'encodings.aliases' # <_frozen_importlib_external.SourceFileLoader object at 0xb6727a30>
import 'encodings' # <_frozen_importlib_external.SourceFileLoader object at 0xb678b988>
# /usr/lib/python3.9/encodings/__pycache__/utf_8.cpython-39.pyc matches /usr/lib/python3.9/encodings/utf_8.py
# code object from '/usr/lib/python3.9/encodings/__pycache__/utf_8.cpython-39.pyc'
import 'encodings.utf_8' # <_frozen_importlib_external.SourceFileLoader object at 0xb678b8e0>
import '_signal' # <class '_frozen_importlib.BuiltinImporter'>
# /usr/lib/python3.9/encodings/__pycache__/latin_1.cpython-39.pyc matches /usr/lib/python3.9/encodings/latin_1.py
# code object from '/usr/lib/python3.9/encodings/__pycache__/latin_1.cpython-39.pyc'
import 'encodings.latin_1' # <_frozen_importlib_external.SourceFileLoader object at 0xb6727b38>
# /usr/lib/python3.9/__pycache__/io.cpython-39.pyc matches /usr/lib/python3.9/io.py
# code object from '/usr/lib/python3.9/__pycache__/io.cpython-39.pyc'
# /usr/lib/python3.9/__pycache__/abc.cpython-39.pyc matches /usr/lib/python3.9/abc.py
# code object from '/usr/lib/python3.9/__pycache__/abc.cpython-39.pyc'
import '_abc' # <class '_frozen_importlib.BuiltinImporter'>
import 'abc' # <_frozen_importlib_external.SourceFileLoader object at 0xb6727e80>
import 'io' # <_frozen_importlib_external.SourceFileLoader object at 0xb6727d00>
# /usr/lib/python3.9/__pycache__/site.cpython-39.pyc matches /usr/lib/python3.9/site.py
# code object from '/usr/lib/python3.9/__pycache__/site.cpython-39.pyc'
# /usr/lib/python3.9/__pycache__/os.cpython-39.pyc matches /usr/lib/python3.9/os.py
# code object from '/usr/lib/python3.9/__pycache__/os.cpython-39.pyc'
# /usr/lib/python3.9/__pycache__/stat.cpython-39.pyc matches /usr/lib/python3.9/stat.py
# code object from '/usr/lib/python3.9/__pycache__/stat.cpython-39.pyc'
import '_stat' # <class '_frozen_importlib.BuiltinImporter'>
import 'stat' # <_frozen_importlib_external.SourceFileLoader object at 0xb673cf40>
# /usr/lib/python3.9/__pycache__/_collections_abc.cpython-39.pyc matches /usr/lib/python3.9/_collections_abc.py
# code object from '/usr/lib/python3.9/__pycache__/_collections_abc.cpython-39.pyc'
import '_collections_abc' # <_frozen_importlib_external.SourceFileLoader object at 0xb673cf58>
# /usr/lib/python3.9/__pycache__/posixpath.cpython-39.pyc matches /usr/lib/python3.9/posixpath.py
# code object from '/usr/lib/python3.9/__pycache__/posixpath.cpython-39.pyc'
# /usr/lib/python3.9/__pycache__/genericpath.cpython-39.pyc matches /usr/lib/python3.9/genericpath.py
# code object from '/usr/lib/python3.9/__pycache__/genericpath.cpython-39.pyc'
import 'genericpath' # <_frozen_importlib_external.SourceFileLoader object at 0xb66e67c0>
import 'posixpath' # <_frozen_importlib_external.SourceFileLoader object at 0xb66d2448>
import 'os' # <_frozen_importlib_external.SourceFileLoader object at 0xb673c628>
# /usr/lib/python3.9/__pycache__/_sitebuiltins.cpython-39.pyc matches /usr/lib/python3.9/_sitebuiltins.py
# code object from '/usr/lib/python3.9/__pycache__/_sitebuiltins.cpython-39.pyc'
import '_sitebuiltins' # <_frozen_importlib_external.SourceFileLoader object at 0xb673cd00>
# /usr/lib/python3.9/__pycache__/_bootlocale.cpython-39.pyc matches /usr/lib/python3.9/_bootlocale.py
# code object from '/usr/lib/python3.9/__pycache__/_bootlocale.cpython-39.pyc'
import '_locale' # <class '_frozen_importlib.BuiltinImporter'>
import '_bootlocale' # <_frozen_importlib_external.SourceFileLoader object at 0xb66e6a78>
# /home/pi/Inkycal/venv/lib/python3.9/site-packages/_distutils_hack/__pycache__/__init__.cpython-39.pyc matches /home/pi/Inkycal/venv/lib/python3.9/site-packages/_distutils_hack/__init__.py
# code object from '/home/pi/Inkycal/venv/lib/python3.9/site-packages/_distutils_hack/__pycache__/__init__.cpython-39.pyc'
import '_distutils_hack' # <_frozen_importlib_external.SourceFileLoader object at 0xb66e6e08>
# /usr/lib/python3.9/__pycache__/types.cpython-39.pyc matches /usr/lib/python3.9/types.py
# code object from '/usr/lib/python3.9/__pycache__/types.cpython-39.pyc'
import 'types' # <_frozen_importlib_external.SourceFileLoader object at 0xb66ff508>
# /usr/lib/python3.9/importlib/__pycache__/__init__.cpython-39.pyc matches /usr/lib/python3.9/importlib/__init__.py
# code object from '/usr/lib/python3.9/importlib/__pycache__/__init__.cpython-39.pyc'
# /usr/lib/python3.9/__pycache__/warnings.cpython-39.pyc matches /usr/lib/python3.9/warnings.py
# code object from '/usr/lib/python3.9/__pycache__/warnings.cpython-39.pyc'
import 'warnings' # <_frozen_importlib_external.SourceFileLoader object at 0xb66ffac0>
import 'importlib' # <_frozen_importlib_external.SourceFileLoader object at 0xb66ff8f8>
# /usr/lib/python3.9/importlib/__pycache__/util.cpython-39.pyc matches /usr/lib/python3.9/importlib/util.py
# code object from '/usr/lib/python3.9/importlib/__pycache__/util.cpython-39.pyc'
# /usr/lib/python3.9/importlib/__pycache__/abc.cpython-39.pyc matches /usr/lib/python3.9/importlib/abc.py
# code object from '/usr/lib/python3.9/importlib/__pycache__/abc.cpython-39.pyc'
# /usr/lib/python3.9/importlib/__pycache__/machinery.cpython-39.pyc matches /usr/lib/python3.9/importlib/machinery.py
# code object from '/usr/lib/python3.9/importlib/__pycache__/machinery.cpython-39.pyc'
import 'importlib.machinery' # <_frozen_importlib_external.SourceFileLoader object at 0xb668c790>
# /usr/lib/python3.9/__pycache__/typing.cpython-39.pyc matches /usr/lib/python3.9/typing.py
# code object from '/usr/lib/python3.9/__pycache__/typing.cpython-39.pyc'
# /usr/lib/python3.9/collections/__pycache__/__init__.cpython-39.pyc matches /usr/lib/python3.9/collections/__init__.py
# code object from '/usr/lib/python3.9/collections/__pycache__/__init__.cpython-39.pyc'
# /usr/lib/python3.9/__pycache__/heapq.cpython-39.pyc matches /usr/lib/python3.9/heapq.py
# code object from '/usr/lib/python3.9/__pycache__/heapq.cpython-39.pyc'
import '_heapq' # <class '_frozen_importlib.BuiltinImporter'>
import 'heapq' # <_frozen_importlib_external.SourceFileLoader object at 0xb66c3148>
import 'itertools' # <class '_frozen_importlib.BuiltinImporter'>
# /usr/lib/python3.9/__pycache__/keyword.cpython-39.pyc matches /usr/lib/python3.9/keyword.py
# code object from '/usr/lib/python3.9/__pycache__/keyword.cpython-39.pyc'
import 'keyword' # <_frozen_importlib_external.SourceFileLoader object at 0xb66c3400>
# /usr/lib/python3.9/__pycache__/operator.cpython-39.pyc matches /usr/lib/python3.9/operator.py
# code object from '/usr/lib/python3.9/__pycache__/operator.cpython-39.pyc'
import '_operator' # <class '_frozen_importlib.BuiltinImporter'>
import 'operator' # <_frozen_importlib_external.SourceFileLoader object at 0xb66c3460>
# /usr/lib/python3.9/__pycache__/reprlib.cpython-39.pyc matches /usr/lib/python3.9/reprlib.py
# code object from '/usr/lib/python3.9/__pycache__/reprlib.cpython-39.pyc'
import 'reprlib' # <_frozen_importlib_external.SourceFileLoader object at 0xb66c3598>
import '_collections' # <class '_frozen_importlib.BuiltinImporter'>
import 'collections' # <_frozen_importlib_external.SourceFileLoader object at 0xb66a7c40>
# /usr/lib/python3.9/collections/__pycache__/abc.cpython-39.pyc matches /usr/lib/python3.9/collections/abc.py
# code object from '/usr/lib/python3.9/collections/__pycache__/abc.cpython-39.pyc'
import 'collections.abc' # <_frozen_importlib_external.SourceFileLoader object at 0xb66a7d60>
# /usr/lib/python3.9/__pycache__/contextlib.cpython-39.pyc matches /usr/lib/python3.9/contextlib.py
# code object from '/usr/lib/python3.9/__pycache__/contextlib.cpython-39.pyc'
# /usr/lib/python3.9/__pycache__/functools.cpython-39.pyc matches /usr/lib/python3.9/functools.py
# code object from '/usr/lib/python3.9/__pycache__/functools.cpython-39.pyc'
import '_functools' # <class '_frozen_importlib.BuiltinImporter'>
import 'functools' # <_frozen_importlib_external.SourceFileLoader object at 0xb6653250>
import 'contextlib' # <_frozen_importlib_external.SourceFileLoader object at 0xb66a7f40>
# /usr/lib/python3.9/__pycache__/re.cpython-39.pyc matches /usr/lib/python3.9/re.py
# code object from '/usr/lib/python3.9/__pycache__/re.cpython-39.pyc'
# /usr/lib/python3.9/__pycache__/enum.cpython-39.pyc matches /usr/lib/python3.9/enum.py
# code object from '/usr/lib/python3.9/__pycache__/enum.cpython-39.pyc'
import 'enum' # <_frozen_importlib_external.SourceFileLoader object at 0xb6653fe8>
# /usr/lib/python3.9/__pycache__/sre_compile.cpython-39.pyc matches /usr/lib/python3.9/sre_compile.py
# code object from '/usr/lib/python3.9/__pycache__/sre_compile.cpython-39.pyc'
import '_sre' # <class '_frozen_importlib.BuiltinImporter'>
# /usr/lib/python3.9/__pycache__/sre_parse.cpython-39.pyc matches /usr/lib/python3.9/sre_parse.py
# code object from '/usr/lib/python3.9/__pycache__/sre_parse.cpython-39.pyc'
# /usr/lib/python3.9/__pycache__/sre_constants.cpython-39.pyc matches /usr/lib/python3.9/sre_constants.py
# code object from '/usr/lib/python3.9/__pycache__/sre_constants.cpython-39.pyc'
import 'sre_constants' # <_frozen_importlib_external.SourceFileLoader object at 0xb6687190>
import 'sre_parse' # <_frozen_importlib_external.SourceFileLoader object at 0xb666ed90>
import 'sre_compile' # <_frozen_importlib_external.SourceFileLoader object at 0xb666ea00>
# /usr/lib/python3.9/__pycache__/copyreg.cpython-39.pyc matches /usr/lib/python3.9/copyreg.py
# code object from '/usr/lib/python3.9/__pycache__/copyreg.cpython-39.pyc'
import 'copyreg' # <_frozen_importlib_external.SourceFileLoader object at 0xb6687dc0>
import 're' # <_frozen_importlib_external.SourceFileLoader object at 0xb66c39e8>
import 'typing' # <_frozen_importlib_external.SourceFileLoader object at 0xb668c8e0>
import 'importlib.abc' # <_frozen_importlib_external.SourceFileLoader object at 0xb66fffa0>
import 'importlib.util' # <_frozen_importlib_external.SourceFileLoader object at 0xb66ff9b8>
# possible namespace for /home/pi/Inkycal/venv/lib/python3.9/site-packages/mpl_toolkits
# possible namespace for /home/pi/Inkycal/venv/lib/python3.9/site-packages/mpl_toolkits
# destroy mpl_toolkits
# /usr/lib/python3.9/__pycache__/sitecustomize.cpython-39.pyc matches /usr/lib/python3.9/sitecustomize.py
# code object from '/usr/lib/python3.9/__pycache__/sitecustomize.cpython-39.pyc'
import 'sitecustomize' # <_frozen_importlib_external.SourceFileLoader object at 0xb66ff208>
import 'site' # <_frozen_importlib_external.SourceFileLoader object at 0xb673c370>
Python 3.9.2 (default, Mar 12 2021, 04:06:34) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
# extension module 'readline' loaded from '/usr/lib/python3.9/lib-dynload/readline.cpython-39-arm-linux-gnueabihf.so'
# extension module 'readline' executed from '/usr/lib/python3.9/lib-dynload/readline.cpython-39-arm-linux-gnueabihf.so'
import 'readline' # <_frozen_importlib_external.ExtensionFileLoader object at 0xb66e6c88>
import 'atexit' # <class '_frozen_importlib.BuiltinImporter'>
# /usr/lib/python3.9/__pycache__/rlcompleter.cpython-39.pyc matches /usr/lib/python3.9/rlcompleter.py
# code object from '/usr/lib/python3.9/__pycache__/rlcompleter.cpython-39.pyc'
import 'rlcompleter' # <_frozen_importlib_external.SourceFileLoader object at 0xb66ff2c8>
```
>>>

**Comment by tinolinoh** [comment] 2023-04-07 11:11
Hi there,

first of all, thank you for your amazing work! 
Unfortunately I am experiencing exactly the same issue:

![Capture](https://user-images.githubusercontent.com/50471151/230599297-4df4529b-e0da-42b5-9936-652d2be87d15.JPG)

Regards,

Tino

**Comment by lukasMega** [comment] 2023-04-12 18:25
The same here with 2.0.2 on Raspberry Pi Zero W (ARM v6) 
`Linux RPi0paper 6.1.21+ #1642 Mon Apr  3 17:19:14 BST 2023 armv6l GNU/Linux`

**Comment by lukasMega** [comment] 2023-04-12 20:25
I found a solution (most probably). At least I managed to running on my setup:
```
device:  Raspberry Pi Zero W (ARM v6)
OS:      DietPi
kernel:  Linux RPi0paper 6.1.21+ #1642 Mon Apr  3 17:19:14 BST 2023 armv6l GNU/Linux
Inkycal: 2.0.2
```

if command:
`python3 -c "import yfinance"` outputs: `Illegal instruction` then: 
 - comment out **stocks** related code in: `inkycal/init.py` and `inkycal/modules/init.py`

try running inkycal...

for `ImportError: The _imagingft C module is not installed`:
 - install: `sudo apt install libfreetype6-dev`

for `PermissionError` (`PermissionError: [Errno 13] Permission denied`):
 and also `RuntimeError: No access to /dev/mem`:

 - I'm not sure what helped, but I executed:
 -- `sudo chmod 666 /dev/spidev0.0`
-- `sudo adduser dietpi gpio`
-- `sudo usermod -a -G gpio dietpi`
 - note that my user is not `pi` but `dietpi`

---

and finally log out and log in (or restart). DONE 🏁

**Comment by aceisace** [comment] 2023-04-16 19:22
I've added the suggested modifications here #251 . @lukasMega  Could you take a look at the changes to ensure they are correct before merging?

**Comment by aceisace** [comment] 2023-05-10 11:56
Closing this issue as the problem is resolved and the actions are working again. If you feel a need to re-open this issue, please do so.

**Closed by aceisace** 2023-05-10 11:56 UTC
Labels: in progress
